name: C/C++ CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt-get update && sudo apt-get install cmake -y
    - name: recipe
      run: cmake ./hw-01 -B hw-01/build/ -DPATCH_VERSION=${{ github.run_number }}
    - name: build
      run: cmake --build hw-01/build/
    - name: run
      run: ./hw-01/build/helloworld_cli
    - name: release
      uses: actions/create-release@v1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
