name: C/C++ CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile 
      run: sudo apt-get update && sudo apt-get install cmake -y
      run: cmake . -DPATCH_VERSION=${{ gtihub.run_number }}
      run: cmake . -DPATCH_VERSION=${{ gtihub.run_number }}
    - name: run
      run: cmake --build 
      run: ./helloworld_cli ${{github.run_number}}
    - name: release
      uses: actions/release@v1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
