name: C/C++ CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile 
      run: g++ hw-01/helloworld.cpp
    - name: run
      run: hw-01/./a.out ${{github.run_number}}
