name: C/C++ CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile 
      run: g++ hw-01/helloworld.cpp
    - name: run
      run: ./a.out ${{github.run_number}}
    - name: release
      run: gh release create v0.0.${{github.run_number}}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
