name: 'C++ IP address filtration'

on:
  push:
    branches:
      - hw-02
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install cmake
        run: sudo apt-get update && sudo apt-get install cmake
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - name: Install gmock manually
        run: sudo apt-get install libgmock-dev && cd /usr/src/googletest/googlemock/ && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib
      - name: Recipe
        run: cmake hw-02/ -B hw-02/build/ -DPATCH_VERSION=${{ github.run_number }}
      - name: Build
        run: cmake --build hw-02/build
      - name: Run Tests
        run: cmake --build hw-02/build/ --target test
      - name: Build Package
        run: ls && cmake --build hw-02/build/ --target package
      - name: Run
        run: cat hw-02/resources/ip_filter.tsv | ./hw-02/build/ip-filter | md5sum
      - name: Release
        id: release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: 1.${{ github.run_number }}
            release_name: IP-Filter ${{ github.run_number }}
            draft: false
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.release.outputs.upload_url }}
            asset_path: ./hw-02/build/ip-filter-1.0.${{ github.run_number }}-Linux.deb
            asset_name: ip-filter-1.0.${{ github.run_number }}-Linux.deb
            asset_content_type: application/vnd.debian.binary-package
